### ISSUE TITLE
Calibration tool arguments

### ISSUE THREAD

**Issue by saratrajput** [fdcl-gwu/aruco-markers#2]
In the camera_calibration code, the marker side length and separation between two separate markers is mentioned in meters. So, this should be measured when you print the board. Thus in README, the steps should be changed from:
./camera_calibration -d=16 -dp=../detector_params.yml -h=2 -w=4 -l=200 -s=100 ../../calibration_params.yml 

TO

./camera_calibration -d=16 -dp=../detector_params.yml -h=2 -w=4 -l=\<measured length in meters\> -s=\<measured length in meters\> ../../calibration_params.yml

**Comment by kanishkegb** [comment]
Thank you for pointing this out. Yes, you are correct. I guess I copied and pasted the arguments from the marker generation commands, and forgot to change that.

Issue corrected in [e9b1454](https://github.com/fdcl-gwu/aruco-markers/commit/e9b14544882fc0b2e52ab1e242ba09cdb9f86e5e).
