### ISSUE TITLE
Using with diamond Aruco

### ISSUE THREAD

**Issue by sanjaysswami** [fdcl-gwu/aruco-markers#5]
@kanishkegb Hey I have diamond shaped aruco printed. Can I use your code? Will it give pose for each aruco relative to each other or how will it work?

Another thing- how much accurate pose we can get?

**Comment by kanishkegb** [comment]
I am not sure what you mean by a diamond shaped marker. Is that the diamond marker as stated [here](https://docs.opencv.org/3.4.2/d9/d6d/tutorial_table_of_content_aruco.html)?

This repository does not implement a different method to estimate the pose from a fiducial marker. We simply use the [ArUco library](https://www.uco.es/investiga/grupos/ava/node/26) implemented in OpenCV,  as mentioned in the ReadMe. If your marker can be read through that, it will work. The pose estimation gives you the rotation of the marker relative to the camera frame (the camera frame is defined [here](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d)).

About accuracy, I do not have a numerical value for the accuracy, but it is fairly accurate. The more markers you have on the board, greater the accuracy.

**Comment by sanjaysswami** [comment]
> I am not sure what you mean by a diamond shaped marker. Is that the diamond marker as stated [here](https://docs.opencv.org/3.4.2/d9/d6d/tutorial_table_of_content_aruco.html)?
> 
> This repository does not implement a different method to estimate the pose from a fiducial marker. We simply use the [ArUco library](https://www.uco.es/investiga/grupos/ava/node/26) implemented in OpenCV, as mentioned in the ReadMe. If your marker can be read through that, it will work. The pose estimation gives you the rotation of the marker relative to the camera frame (the camera frame is defined [here](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga3207604e4b1a1758aa66acb6ed5aa65d)).
> 
> About accuracy, I do not have a numerical value for the accuracy, but it is fairly accurate. The more markers you have on the board, greater the accuracy.

Yes I was talking about the same diamond marker. So you are telling that if the marker id is present in the library then it will give me trans-vector and rot-vector right?

**Comment by kanishkegb** [comment]
Yes, it should as long as you update the code to use the dictionary with the relevant marker, or pass the correct library ID through the argument `-d`.
